services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: wms_db_vector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: wms_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: wms_ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  fastapi-app:
    build: .
    container_name: wms_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres-vector
      - ollama
    env_file:
      - .env
    environment:
      - INITIAL_ADMIN_USER=admin
      - INITIAL_ADMIN_PASS=admin
    volumes:
      - ./app:/code/app
    restart: unless-stopped

volumes:
  pgdata: